### ISSUE TITLE
"Select" command does not work as instance method

### ISSUE THREAD

**Issue by JacobAnter** [biotite-dev/biotite2pymol#1]
Hello,

I encountered the problem that although it is stated in the Ammolite documentation that the "select" command is supported as instance method, applying this method to a PyMol object does not return a PyMol object, but a 'NoneType ' object. Here is the sample code:

```python
# Import libraries
from biotite.structure.io.pdb import PDBFile
import numpy as np
import ammolite

ammolite.reset()

# Working on exercise one dealing with the ternary complex between
# Hsp 90, FKBP51 and P23
# Loading the structure into an AtomArray
pdb_file = PDBFile.read("7l7i.pdb")
atom_array = pdb_file.get_structure(
    model=1,
    include_bonds=True
)

# Converting the AtomArray to a PyMol object
pymol_ternary_complex = ammolite.PyMOLObject.from_structure(atom_array)
```

The variable ``pymol_ternary_complex`` stores a ``ammolite.PyMOLObject``, as the following line of code demonstrates:

```
print(type(pymol_ternary_complex))
```

If ``pymol_ternary_complex``, however, is used in order to make a selection via PyMol's ``select`` command, as shown in the following line of code:

```
pymol_ternary_complex.select(
    name="fkbp51",
    selection= atom_array.chain_id == "C"
)
```

the corresponding variable stores an object of type ``NoneType``, raising an ``AttributeError`` when trying to perform operations on the selection, such as changing its colour.

Is this really a bug or do I merely have overlooked something in the documentation?

Thanks in advance.

Kind regards

**Comment by padix-key** [comment]
Hi, the method works as intended: It creates a *PyMOL* selection with the given name, which can be used in *PyMOL* commands, is visible in the GUI and can also be given as selection in `PyMOLObject` methods (though it is recommended to use boolean masks of the underlying `AtomArray` instead):

```python
pymol_ternary_complex.select(
    name="fkbp51",
    selection= atom_array.chain_id == "C"
)
pymol_ternary_complex.color("blue", selection="fkbp51")
```

Returning a `PyMOLObject` in `select()` would be misleading, since a selection is rather a pointer to certain atoms in a `PyMOLObject` than a `PyMOLObject` itself.
